markdown: rdiscount
pygments: true
auto: true
lsi: true
tags: ['one', 'two']
word: 'It is nevar put with the wrong end in front.'
permalink: /lisblog/:categories/:title.lisb
comments :
  provider : disqus
  disqus :
    short_name : tonlog
  livefyre :
    site_id : 123
  intensedebate :
    account : 123abc
  facebook :
    appid : 123
    num_posts: 5
    width: 580
    colorscheme: light

analytics :
  provider : google
  google : 
      tracking_id : 'UA-40397445-1'
  getclicky :
    site_id :
